pool:
  vmImage: 'windows-2019'

container:
   image: mcr.microsoft.com/windows/servercore:ltsc2019
   options: --mac-address 92:d0:c6:0a:29:33

steps:
- task: PowerShell@2
    inputs:
       targetType: 'inline'
       script: |
         $connectTestResult = Test-NetConnection -ComputerName mystorage.file.core.windows.net -Port 445
         if ($connectTestResult.TcpTestSucceeded) {
             cmd.exe /C "cmdkey /add:`"mystorage.file.core.windows.net`" /user:`"Azure\$(storage.account)`" /pass:`"$(storage.key)`""
             # Mount the drive
             New-PSDrive -Name $(storage.drive) -PSProvider FileSystem -Root "$(storage.unc)" -Persist
             dir z:
         }
         else {
              Write-Error -Message "Unable to reach the Azure storage account via port 445. Check to make sure your organization or ISP is not blocking port 445, or use Azure P2S VPN, Azure S2S VPN, or Express Route to tunnel SMB traffic over a different port."
         }
     displayName: "Mount azure file share to Z"

- powershell: ipconfig /all
- powershell: dir .
- powershell: .\InstallShield2018R2StandaloneBuild.exe /s /v"ADDLOCAL=ALL /qn"
- powershell: start-sleep -s 60
- powershell: cd C:\
- powershell: cd "C:\Program Files (x86)\InstallShield\2018 SAB\System"
- powershell: .\IsCmdBld.exe
