pool:
  vmImage: 'windows-2019'

container:
   image: mcr.microsoft.com/windows/servercore:ltsc2019
   options: --mac-address 92:d0:c6:0a:29:33

steps:
- task: DownloadFileshareArtifacts@1
  inputs:
    filesharePath: \\gitlabstoragetest.file.core.windows.net\gitlabshare
    artifactName: InstallShield2018R2StandaloneBuild.exe
    downloadPath: '$(System.ArtifactsDirectory)' 

- powershell: ipconfig /all
- powershell: dir .
- powershell: cd $(System.ArtifactsDirectory)
- powershell: .\InstallShield2018R2StandaloneBuild.exe /s /v"ADDLOCAL=ALL /qn"
- powershell: start-sleep -s 60
- powershell: cd C:\
- powershell: cd "C:\Program Files (x86)\InstallShield\2018 SAB\System"
- powershell: .\IsCmdBld.exe
