pool:
  vmImage: 'windows-2019'

container:
   image: mcr.microsoft.com/windows/servercore@sha256:0594b3bb67e2b5e57ab4414d7ce012a72582a6094b04b536c421ea1a23b7e7c7
   options: --mac-address 92:d0:c6:0a:29:33



steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
        $connectTestResult = Test-NetConnection -ComputerName gitlabstoragetest.file.core.windows.net -Port 445
        if ($connectTestResult.TcpTestSucceeded) {
        # Save the password so the drive will persist on reboot
        cmd.exe /C "cmdkey /add:`"gitlabstoragetest.file.core.windows.net`" /user:`"Azure\gitlabstoragetest`" /pass:`"h0rN8ScqtXVERxRDdr9REwBYcvKc5umoV8E5jIhzE5ViLtXIN5YlMnAsk5/eURMeW/SQ1jwzijbMBDIl/M67ww==`""
        # Mount the drive
        New-PSDrive -Name Z -PSProvider FileSystem -Root "\\gitlabstoragetest.file.core.windows.net\gitlabshare" -Persist
        } else {
        Write-Error -Message "Unable to reach the Azure storage account via port 445. Check to make sure your organization or ISP is not blocking port 445, or use Azure P2S VPN, Azure S2S VPN, or Express Route to tunnel SMB traffic over a different port."
        }
        get-content z:\aaa.txt
        copy-item z:\InstallShield2018R2StandaloneBuild.exe -Destination .
        .\InstallShield2018R2StandaloneBuild.exe /s /v"INSTALLLEVEL=101 SABCONTAINER=1 /qn"
        start-sleep -s 60
        ipconfig /all
        Get-Childitem –Path "C:\Program Files (x86)\InstallShield\2018 SAB\System" | foreach-object {$_.fullname}
    displayName: "Mount azure file share to Z"


