pool:
  vmImage: 'windows-2019'

container:
   image: mcr.microsoft.com/windows/servercore@sha256:0594b3bb67e2b5e57ab4414d7ce012a72582a6094b04b536c421ea1a23b7e7c7
   options: --mac-address 00:15:5D:46:A3:0F



steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
        go
    displayName: "Mount azure file share to Z"


