pool:
  vmImage: 'windows-2019'

container:
   image: mcr.microsoft.com/windows/servercore:ltsc2019
   options: --mac-address 92:d0:c6:0a:29:33
steps:
- script: ipconfig /all
- script: dir .
- script: powershell.exe .\fileshare.ps1
- script: net use
- script: Z:
- script: .\InstallShield2019R3StandaloneBuild.exe /s /v"ADDLOCAL=ALL /qn"
- script: timeout 60
- script: C:
- script: cd "C:\Program Files (x86)\InstallShield\2018 SAB\System"
- script: .\IsCmdBld.exe
